### ISSUE TITLE
Error Log on Startup 

### ISSUE THREAD

**Issue by mjlogg21** [GarbageDayIsHereToStay/Zeta-Reticulans#1]
https://gist.github.com/HugsLibRecordKeeper/fe251d729d7e934286c4ff0c2b81632c
"Mod GarbageDayIsHereToStay.ZetaReticulans.GDIHTSZR has multiple Verse.(insert def type here)Defs named (insert name here). Skipping.." is written on about 60 lines in red on every startup. Don't know if it actually affects gameplay or not. Reticulans appear to work fine.

**Comment by GarbageDayIsHereToStay** [comment]
I just found this, sorry for the delayed response. This isn't something i'm running into/ have had reported.

From the looks of things I'm guessing you accidentally made x2 copies of the mod in you folder and the game is reading all the defs twice.
